require("plugins.nvim-web-devicons")
require("plugins.nvui")
require("plugins.base46")
require("plugins.noice")
require("plugins.nvim-treesitter")
require("plugins.mason")
require("plugins.mason-lspconfig")
require("plugins.mini-pairs")
require("plugins.nvim-tree")
require("plugins.tiny-inline-diagnostic")
require("plugins.conform")
require("plugins.blink-cmp")
require("plugins.nvim-ufo")
require("plugins.edgy")
require("plugins.mini-ai")
require("plugins.toggleterm")
require("plugins.luasnip")
require("nio")
require("plugins.dap-ui")
require("plugins.nvim-dap.init")
require("plugins.nvim-dap-virtual-text")
require("plugins.typst-preview")
require("plugins.comment")
<<<<<<< HEAD
require("plugins.smear-cursor")
-- require("plugins.crates-nvim")
=======
>>>>>>> 37b385c330b8200e74cd17bb0c3510017b29254c

-- Possible to immediately execute code which depends on the added plugin
